//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incentive
    {
        public string EMPLOYEE_REF_ID { get; set; }
        public string INCENTIVE_DATE { get; set; }
        public Nullable<int> INCENTIVE_AMOUNT { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
